// Generated by https://quicktype.io

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Balance
    {
        [JsonProperty("rows")]
        public Row[] Rows { get; set; }

        [JsonProperty("more")]
        public bool More { get; set; }

        [JsonProperty("next_key")]
        public string NextKey { get; set; }
    }

    public partial class Row
    {
        [JsonProperty("balance")]
        public string Balance { get; set; }
    }

    public partial class Balance
    {
        public static Balance FromJson(string json) => JsonConvert.DeserializeObject<Balance>(json, QuickType.Converter.Settings);
    }
}
